### ISSUE TITLE
[PROFILE REVIEW]

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [opensourcecommunity-hub/join-the-community#42]
### GitHub Profile Link:- 
`https://github.com/Programming-School-Pro-Coding`

You can also join our Discord community [here](https://discord.gg/g7FmxB9uZp)
Feel free to check out other cool repositories of the Open Source Community [here](https://github.com/opensourcecommunity-hub)

**Comment by Susmita-Dey** [comment]
Hey @Programming-School-Pro-Coding 

Make the following changes:
- Fix the broken items
![image](https://user-images.githubusercontent.com/79099734/188918114-3f145272-aaad-4963-a8f4-e7f591b28c2a.png)
- Align stats side by side to reduce profile size as it's becoming too long
- Put the blogs section a little above to reach more viewers
- Remove recent activity as it seems duplicate because you already have it below generated by GitHub itself
- Align some items in the center
- Align the trophies in 1 line to remove the extra blank space
